#!/bin/bash

extensions=(
adpyke.codesnap
arcticicestudio.nord-visual-studio-code
bierner.markdown-mermaid
cschlosser.doxdocgen
DavidAnson.vscode-markdownlint
dustypomerleau.rust-syntax
eamodio.gitlens
ecmel.vscode-html-css
emmanuelbeziat.vscode-great-icons
Equinusocio.vsc-community-material-theme
equinusocio.vsc-material-theme-icons
esbenp.prettier-vscode
fernandoescolar.vscode-solution-explorer
file-icons.file-icons
firefox-devtools.vscode-firefox-debug
formulahendry.vscode-mysql
Gaardsholt.vscode-whatthecommit
gamunu.vscode-yarn
GitHub.copilot
GitHub.copilot-chat
GitLab.gitlab-workflow
GrapeCity.gc-excelviewer
Gruntfuggly.todo-tree
hashicorp.terraform
hediet.vscode-drawio
jeff-hykin.better-cpp-syntax
josetr.cmake-language-support-vscode
madprops.nordico
mcright.auto-save
ms-azuretools.vscode-docker
ms-dotnettools.csharp
ms-dotnettools.vscode-dotnet-runtime
ms-kubernetes-tools.vscode-kubernetes-tools
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.powershell
ms-vscode.remote-explorer
mushan.vscode-paste-image
plibither8.remove-comments
Ransh.ransh
redhat.vscode-yaml
rokoroku.vscode-theme-darcula
rust-lang.rust-analyzer
sainnhe.gruvbox-material
sidthesloth.html5-boilerplate
SolarLiner.linux-themes
streetsidesoftware.code-spell-checker
streetsidesoftware.code-spell-checker-german
tal7aouy.icons
teabyii.ayu
tinkertrain.theme-panda
tomoki1207.pdf
twxs.cmake
vscode-icons-team.vscode-icons
vscodevim.vim
wayou.vscode-icons-mac
xdebug.php-debug
xdebug.php-pack
yzane.markdown-pdf
yzhang.markdown-all-in-one
zamerick.vscode-caddyfile-syntax
zobo.php-intellisense
)

for extension in "${extensions[@]}"
do
   codium --install-extension $extension
done

